version: '3'

services:
  redis-server:
    container_name: redis-server
    image: redislabs/redismod:latest
    ports:
      - 6379:6379
    volumes:
      - redis-stack-data:/data:ro
  
  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    ports:
      - "13333:8001"
    depends_on:
      - redis-server
    links:
      - "redis-server"
    
volumes:
  redis-stack-data: